### ISSUE TITLE
Fix nginx changed filter

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/ansible-nginx#10]
Running role on ansible 2.9.0 fails with: `The conditional check 'nginx_delete_default_site | bool and delete_default_site | changed' failed. The error was: template error while templating string: no filter named 'changed'.`

Changing to `delete_default_site is changed` works.

<Details>
TASK [azavea.nginx : Delete default web root] **********************************
fatal: [app]: FAILED! => {"msg": "The conditional check 'nginx_delete_default_site | bool and delete_default_site | changed' failed. The error was: template error while templating string: no filter named 'changed'. String: {% if nginx_delete_default_site | bool and delete_default_site | changed %} True {% else %} False {% endif %}\n\nThe error appears to be in '/projects/cac-tripplanner/deployment/ansible/roles/azavea.nginx/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Delete default web root\n  ^ here\n"}
</Details>

**Comment by Abdelhady** [comment]
I hope this would be merged soon, I had to downgrade Ansible itself to get around this issue.
